name: Deploy Static Website to GitHub Pages

on:
  push:
    branches:
      - master    # Trigger on everty push to master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - uses: actions/checkout@v4

      # 2. Setup .NET (needed if you later have Blazor or other .NET build)
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # 3. Publish the project (optional, but ensures wwwroot exists)
      - name: Publish Project
        run: dotnet publish -c Release -o published

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: published/wwwroot

  deploy:
    environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      # 4. Deploy wwwroot to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4